import os
import uuid
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field

from .context import ContextNode
from .resolver import ParamResolver

@dataclass
class Job:
    id: str
    target_path: str
    processor_name: str
    params: Dict[str, Any]
    context: Dict[str, Any]
    dependencies: List[str] = field(default_factory=list)
    
    # Hash for resume capability
    # We will compute this later or now. 
    # Let's add a placeholder.
    content_hash: str = ""

class Planner:
    def __init__(self, resolver: ParamResolver):
        self.resolver = resolver

    def plan(self, target_structure: List[Dict], context_tree: ContextNode) -> List[Job]:
        """
        Generates a list of jobs based on the target structure and context tree.
        """
        all_jobs = []
        # We start with the root context node (dataset level)
        # But target_structure is a list of roots.
        
        # Initial dependencies: None
        last_layer_jobs = [] 
        
        for config_node in target_structure:
            new_jobs = self._process_node(config_node, context_tree, last_layer_jobs)
            all_jobs.extend(new_jobs)
            # For the top level, sequential processing of structure nodes?
            # Usually yes.
            last_layer_jobs = [j.id for j in new_jobs]

        return all_jobs

    def _process_node(self, 
                      config_node: Dict, 
                      context_node: ContextNode, 
                      dependency_ids: List[str]) -> List[Job]:
        
        node_type = config_node.get("type", "file")
        iterator_name = config_node.get("iterator")
        
        jobs = []

        # 1. Determine Context(s) to operate on
        target_contexts = []
        if iterator_name:
            
            if context_node.iterator_name == iterator_name:
                 # We are already here (e.g. recursive call). 
                 # But usually _process_node is called from parent.
                 target_contexts = [context_node]
            else:
                 # Find direct children matching iterator?
                 # ContextNode.find_descendants finds all. 
                 # But we usually only want the *immediate* next level of iterator 
                 # relative to where we are in the structure.
                 # Simplified: Just find direct children that are this iterator.
                 target_contexts = [child for child in context_node.children if child.iterator_name == iterator_name]
        else:
            # Single execution context (Current Node)
            target_contexts = [context_node]

        # 2. Process for each context
        for ctx in target_contexts:
            current_jobs = self._create_jobs_for_context(config_node, ctx, dependency_ids)
            jobs.extend(current_jobs)
            
        return jobs

    def _create_jobs_for_context(self, 
                                 config_node: Dict, 
                                 context_node: ContextNode, 
                                 dependency_ids: List[str]) -> List[Job]:
        
        full_context = context_node.get_full_context()
        
        # Resolve Name
        name_tmpl = config_node.get("name", "unnamed")
        
        return [] # Placeholder, refactoring below

    # Refactored Entry
    def plan_v2(self, target_structure: List[Dict], context_tree: ContextNode) -> List[Job]:
        return self._recurse_structure(target_structure, context_tree, self.resolver.dest_root, [])

    def _recurse_structure(self, 
                           structure_list: List[Dict], 
                           context_node: ContextNode, 
                           parent_target_path: str,
                           dependencies: List[str]) -> List[Job]:
        
        all_jobs_in_sequence = []
        
        # "previous_siblings" dependencies
        # Initially, the first child depends on `dependencies` passed in (parent's dependencies)
        current_dependencies = list(dependencies)
        
        for config in structure_list:
            node_jobs = []
            
            iterator_name = config.get("iterator")
            
            # Determine contexts
            contexts_to_process = []
            if iterator_name:
                # Find children of current context_node that match
                # If context_node IS the parent (e.g. Root), children are Tasks.
                contexts_to_process = [c for c in context_node.children if c.iterator_name == iterator_name]
                # If none found? e.g. empty task list.
            else:
                contexts_to_process = [context_node]
            
            # Collect all jobs generated by this config across all contexts
            # These will become dependencies for the NEXT config in structure_list
            this_step_all_job_ids = []

            for ctx in contexts_to_process:
                # Resolve Name
                raw_name = config.get("name", "")
                resolved_name = self.resolver._resolve_string(raw_name, ctx.get_full_context())
                
                # Full Target Path
                # If parent_target_path is dest_root, and resolved_name is "task_1", path is "root/task_1"
                current_target_path = os.path.join(parent_target_path, resolved_name)
                
                # 1. Create Job for this node (if it has a processor)
                processor_name = config.get("processor")
                
                my_job_id = None
                if processor_name:
                    
                    params = config.get("params", {})
                    resolved_params = self.resolver.resolve(params, ctx.get_full_context(), ctx)
                    
                    job = Job(
                        id=str(uuid.uuid4()),
                        target_path=current_target_path,
                        processor_name=processor_name,
                        params=resolved_params,
                        context=ctx.get_full_context(),
                        dependencies=list(current_dependencies) # Copy
                    )
                    all_jobs_in_sequence.append(job)
                    node_jobs.append(job)
                    my_job_id = job.id
                    this_step_all_job_ids.append(my_job_id)

                # 2. Recurse children
                children_config = config.get("children", [])
                if children_config:
                    # The children depend on:
                    # - The job of the current node (if it exists)
                    # - The dependencies of the current node (if current node has no job, it's a pass-through folder)
                    
                    child_deps = list(current_dependencies)
                    if my_job_id:
                        child_deps.append(my_job_id)
                    
                    child_jobs = self._recurse_structure(
                        children_config, 
                        ctx, 
                        current_target_path, 
                        child_deps
                    )
                    
                    all_jobs_in_sequence.extend(child_jobs)
                    node_jobs.extend(child_jobs)
                    
                    # If this node was just a folder (no processor), 
                    # effectively the "output" of this node is the output of its children.
                    # But for "Implicit Order", the NEXT sibling in `structure_list`
                    # should wait for THIS node and ALL its children to finish.
                    
                    # Collect all IDs from children to add to dependencies of next sibling
                    this_step_all_job_ids.extend([j.id for j in child_jobs])

            # Update dependencies for the next sibling in the list
            # The next sibling must wait for ALL instances of this current config (all iterations)
            current_dependencies = this_step_all_job_ids
            
        return all_jobs_in_sequence

